### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by varemenos** [klaaspieter/chxcode#7]
I'm trying to utilize chxcode while on a fish shell session but I can't source it.

```✖> source /usr/local/share/chxcode/chxcode
/usr/local/share/chxcode/chxcode (line 3): Unsupported use of '='. In fish, please use 'set xcode_search_path ${xcode_search_path-/}'.
from sourcing file /usr/local/share/chxcode/chxcode
source: Error while reading file '/usr/local/share/chxcode/chxcode'
```

I even tried to utilize [bass](https://github.com/edc/bass) but to no avail. I know this is sort of a longshot but any ideas as to how to get it to work?

**Comment by klaaspieter** [comment]
I do not use fish and am hesitant to add and maintain support for a non-POSIX compliant shell. However chxcode was heavily inspired by chruby and they have a similiar issue for fish support (https://github.com/postmodern/chruby/issues/284) where one of the commentors recommends https://github.com/JeanMertz/chruby-fish

Perhaps you can do something similiar with chxcode?
